version: "3.9"

services:
  contract-intel-api:
    build: .
    container_name: contract-intel-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - WEBHOOK_URL=string
      - ENV=development
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
